### ISSUE TITLE
discord status in chinese

### ISSUE THREAD

**Issue by oscarjian** [floxay/ValorantRichPresence#2]
Hello, this tool is awesome, is there any way to show the valorant status in chinese? (since u make the bt-BR one)
i can help to translate cuz this tool is so cool and i want to share it to the valorant community in taiwan 
tks :D

**Comment by floxay** [comment]
Currently no and I'm also not planning to add more language support before a full revamp of the source code.

Also there are multiple open source (and more feature rich) alternatives available on github which you can modify to your needs by now.
